// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viamatica.Infrastructure.Persistence;

#nullable disable

namespace Viamatica.Infrastructure.Migrations
{
    [DbContext(typeof(ViamaticaDbContext))]
    [Migration("20261006033701_AddIsDeletedToContract")]
    partial class AddIsDeletedToContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Viamatica.Domain.Entities.Attention", b =>
                {
                    b.Property<int>("AttentionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttentionId"));

                    b.Property<int>("AttentionStatusStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ClientClientId")
                        .HasColumnType("int");

                    b.Property<int>("TurnTurnId")
                        .HasColumnType("int");

                    b.HasKey("AttentionId");

                    b.HasIndex("AttentionStatusStatusId");

                    b.HasIndex("ClientClientId");

                    b.HasIndex("TurnTurnId")
                        .IsUnique();

                    b.ToTable("Attentions");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.AttentionStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("AttentionStatuses");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.AttentionType", b =>
                {
                    b.Property<string>("AttentionTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttentionTypeId");

                    b.ToTable("AttentionTypes");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Cash", b =>
                {
                    b.Property<int>("CashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CashId"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CashDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CashId");

                    b.ToTable("Cashes");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("ClientClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MethodPaymentMethodPaymentId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusContractStatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ContractId");

                    b.HasIndex("ClientClientId");

                    b.HasIndex("MethodPaymentMethodPaymentId");

                    b.HasIndex("ServiceServiceId");

                    b.HasIndex("StatusContractStatusId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceServiceId")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.HasIndex("ServiceServiceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.MethodPayment", b =>
                {
                    b.Property<int>("MethodPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodPaymentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MethodPaymentId");

                    b.ToTable("MethodPayments");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("ClientClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("ClientClientId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("RolId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SpeedMbps")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.StatusContract", b =>
                {
                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("StatusContracts");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Turn", b =>
                {
                    b.Property<int>("TurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnId"));

                    b.Property<int?>("AttentionId")
                        .HasColumnType("int");

                    b.Property<string>("AttentionTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CashCashId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserGestorId")
                        .HasColumnType("int");

                    b.HasKey("TurnId");

                    b.HasIndex("AttentionTypeId");

                    b.HasIndex("CashCashId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateApproval")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolRolId")
                        .HasColumnType("int");

                    b.Property<int?>("UserApproval")
                        .HasColumnType("int");

                    b.Property<int?>("UserCreate")
                        .HasColumnType("int");

                    b.Property<string>("UserStatusStatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RolRolId");

                    b.HasIndex("UserStatusStatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.UserCash", b =>
                {
                    b.Property<int>("UserUserId")
                        .HasColumnType("int");

                    b.Property<int>("CashCashId")
                        .HasColumnType("int");

                    b.HasKey("UserUserId", "CashCashId");

                    b.HasIndex("CashCashId");

                    b.ToTable("UserCashes");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.UserStatus", b =>
                {
                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("UserStatuses");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Attention", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.AttentionStatus", "AttentionStatus")
                        .WithMany("Attentions")
                        .HasForeignKey("AttentionStatusStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Client", "Client")
                        .WithMany("Attentions")
                        .HasForeignKey("ClientClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Turn", "Turn")
                        .WithOne("Attention")
                        .HasForeignKey("Viamatica.Domain.Entities.Attention", "TurnTurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttentionStatus");

                    b.Navigation("Client");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.MethodPayment", "MethodPayment")
                        .WithMany("Contracts")
                        .HasForeignKey("MethodPaymentMethodPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Service", "Service")
                        .WithMany("Contracts")
                        .HasForeignKey("ServiceServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.StatusContract", "StatusContract")
                        .WithMany("Contracts")
                        .HasForeignKey("StatusContractStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("MethodPayment");

                    b.Navigation("Service");

                    b.Navigation("StatusContract");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Device", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Service", "Service")
                        .WithMany("Devices")
                        .HasForeignKey("ServiceServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Rol", "Rol")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Turn", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.AttentionType", "AttentionType")
                        .WithMany("Turns")
                        .HasForeignKey("AttentionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Cash", "Cash")
                        .WithMany("Turns")
                        .HasForeignKey("CashCashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttentionType");

                    b.Navigation("Cash");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.User", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("UserStatusStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.UserCash", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Cash", "Cash")
                        .WithMany("UserCashes")
                        .HasForeignKey("CashCashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.User", "User")
                        .WithMany("UserCashes")
                        .HasForeignKey("UserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cash");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.AttentionStatus", b =>
                {
                    b.Navigation("Attentions");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.AttentionType", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Cash", b =>
                {
                    b.Navigation("Turns");

                    b.Navigation("UserCashes");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Client", b =>
                {
                    b.Navigation("Attentions");

                    b.Navigation("Contracts");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Menu", b =>
                {
                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.MethodPayment", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Service", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.StatusContract", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Turn", b =>
                {
                    b.Navigation("Attention");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.User", b =>
                {
                    b.Navigation("UserCashes");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.UserStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
